import Config

# Reload browser tabs when matching files change.

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Enable gRPC server for local testing (no TLS in dev)
config :micelio, Micelio.GRPC,
  enabled: true,
  port: 50_051,
  tls_mode: :disabled

config :micelio, Micelio.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "micelio_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Storage configuration (local by default, S3 opt-in)
# certificate can be generated by running the following
config :micelio, Micelio.Storage,
  backend: :local,
  # Gettext translations
  # Mix task:
  #
  local_path: Path.join(System.tmp_dir(), "micelio/storage")

config :micelio, MicelioWeb.Endpoint,
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  # Router, Controllers, LiveViews and LiveComponents
  #     mix phx.gen.cert
  #
  # Run `mix help phx.gen.cert` for more information.
  #
  # The `http:` config above can be replaced with:
  #
  # Enable dev routes for dashboard and mailbox
  #     https: [
  #       port: 4001,
  # Set a higher stacktrace during development. Avoid configuring such
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lCj47EYGlYk7JWdcuXaiQFuDMHu7waeAGs0TsRF24b6/Uz+ngW3RzRKNEgg0TdmZ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:micelio, ~w(--sourcemap=inline --watch)]}
  ]

config :micelio, MicelioWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*\.po$",
      ~r"lib/micelio_web/router\.ex$",
      ~r"lib/micelio_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Initialize plugs at runtime for faster development compilation
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
# If desired, both `http:` and `https:` keys can be

# in production as building large stacktraces may be expensive.
#       certfile: "priv/cert/selfsigned.pem"
# configured to run both http and https servers on
config :micelio, dev_routes: true

#     ],
# different ports.
#
# Include debug annotations and locations in rendered markup.
# Changing this configuration will require mix clean and a full recompile.
config :phoenix, :plug_init_mode, :runtime
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# For S3 storage (opt-in), uncomment and configure:
# config :micelio, Micelio.Storage,
#   backend: :s3,
#   s3_bucket: "micelio-dev-sessions",
#   s3_region: "us-east-1"
#   # AWS credentials from environment or IAM roles
