import Config

# Force using SSL in production. This also sets the "strict-security-transport" header,

# Note we also include the path to a cache manifest
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# containing the digested version of static files. This

# Do not print debug messages in production
# Note `:force_ssl` is required to be set at compile-time.
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :logger, level: :info

config :micelio, MicelioWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :micelio, MicelioWeb.Endpoint,
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  exclude: [
    # paths: ["/health"],
    hosts: ["localhost", "127.0.0.1"]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
